### ISSUE TITLE
PHP Fatal error:  Class 'Evenement\EventEmitter' not found

### ISSUE THREAD

**Issue by rsulym** [lizardmedia/varnish-warmer-magento2#10]
hi, i'm running magento2.2.3 with varnish5 and seems some dependency missed, because i'm getting this error after each console command:

```
PHP Fatal error:  Class 'Evenement\EventEmitter' not found in /vendor/react/http-client/src/Request.php on line 18

Fatal error: Class 'Evenement\EventEmitter' not found in /vendor/react/http-client/src/Request.php on line 18 
```

could you pls advice what's wrong there?

**Comment by maciejslawik** [comment]
Hello.
Do you have `evenement/evenement` dependency installed? It is required by ReactPHP. 
How did you install the module? Using composer or manually?

**Comment by rsulym** [comment]
i've installed it by composer, but what is interesting - there is no dependency in composer.json, which is used during installation, but this dependency exist in file composer.lock, which is not used...
now i'm going to install evenement/evenement manually, thanks for tip.
