### ISSUE TITLE
Composer reports magento/framework incompatible for Magento 2.3.2

### ISSUE THREAD

**Issue by dirkpauw** [lizardmedia/varnish-warmer-magento2#12]
Hi

I'm following the installation instructions, using composer, but this is failing for me as shown in the image here.

![image](https://user-images.githubusercontent.com/24737268/63937130-015d2c80-ca62-11e9-82e4-6fdecab5c1b2.png)

My Magento version is 2.3.2, I don't know what the magento/framework version number is for that.

Thanks

**Comment by maciejslawik** [comment]
I updated the Composer dependencies for the module. Please try now.
