### ISSUE TITLE
Wrong URL if "Add Store Code to Urls" is Yes

### ISSUE THREAD

**Issue by bst2002git** [lizardmedia/varnish-warmer-magento2#14]
Hello
the Url is
https://shop.local/women/tops-women/jackets-women.html
but should be:
https://shop.local/en_us/women/tops-women/jackets-women.html

**Comment by bartoszkubicki** [comment]
Can you provide more information? What url? In which place of module?

**Comment by bst2002git** [comment]
Hallo,
with the magento config "Add Store Code to Urls" all URLs have the language "en_us" or "de_at" as part of the URL.
Executing this:  bin/magento lm-varnish:cache-purge-general --store=106  (store view de_at)
For store 106 all public URLs are https://shop.local/de_at/example.html
but the cache warmer try to get the url https://shop.local/example.html

**Comment by bst2002git** [comment]
Should verbose mode work?

bin/magento lm-varnish:cache-refresh-url --help
Description:
  Clear varnish cache (make PURGE) and re-generate URL

Usage:
  lm-varnish:cache-refresh-url [options] [--] <url>

Arguments:
  url                   Type a URL to PURGE and re-generate

Options:
      --store[=STORE]
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

**Comment by bartoszkubicki** [comment]
Ok now I understand problem, we will come back with some info

**Comment by bartoszkubicki** [comment]
@bst2002git Fix is merged into master, please let me know if now it's working as expected.
