### ISSUE TITLE
version 2.2?

### ISSUE THREAD

**Issue by elfeffe** [lizardmedia/varnish-warmer-magento2#18]
is it not available?
I use PHP 7.3

**Comment by bartoszkubicki** [comment]
@elfeffe it should work on php 7.3. Take a look at https://github.com/lizardmedia/varnish-warmer-magento2/blob/master/composer.json. Try 2.2.0 version of package.

**Comment by bartoszkubicki** [comment]
Ok @elfeffe I understand that is issue is no longer a problem.
