### ISSUE TITLE
Unable to update to 2.2.0 via composer

### ISSUE THREAD

**Issue by nadroj467** [lizardmedia/varnish-warmer-magento2#19]
Hi,

Version 2.2.0 is not available by composer for PHP 7.3. Max version is 2.1.0

composer require lizardmedia/module-varnish-warmer:2.2.0

Thanks

**Comment by nadroj467** [comment]
Any update on this @maciejslawik ? Thanks

**Comment by bartoszkubicki** [comment]
@nadroj467 Thank you for your vigilance! I haven't created tag for this version. I have just fix it. Please let me know, if you can download it.

**Comment by nadroj467** [comment]
@maciejslawik Working now, thanks!
