### ISSUE TITLE
Wrong baseUrl with multiple storeview leads to wrong urls

### ISSUE THREAD

**Issue by gtlt** [lizardmedia/varnish-warmer-magento2#2]
Hi,

I have a site with multiple storeview, each on its own subdomain.
The urls generated should take into account baseUrl per storeview. Currently, only the default one is taken into account. All non default language urls are wrong.

Example :
```
StoreView EN baseUrl : en.mysite.com
StoreView FR baseUrl : fr.mysite.com
```
Currently generated urls : 
```
en.mysite.com/en-url-1
en.mysite.com/fr-url-1
```
it should be : 
```
en.mysite.com/en-url-1
fr.mysite.com/fr-url-1
```
Something like adding \Magento\Store\Model\StoreManagerInterface $storeManager in CacheCleaner to loop on all storeviews and filtering url_rewrite queries on store_id should fix it.

**Comment by maciejslawik** [comment]
Hi,
Thanks for the ticket. We are aware of the issue. I will provide you with an update fixing this issue in a few days.

**Comment by gtlt** [comment]
Great, thank you

**Comment by maciejslawik** [comment]
I updated the module with mutlistore handling.
