### ISSUE TITLE
curl-easy block composer with magento 2.3

### ISSUE THREAD

**Issue by gtlt** [lizardmedia/varnish-warmer-magento2#7]
requirement "stil/curl-easy": "^1.1" block magento 2.3 composer update
I think it is because of curl-easy requiring "symfony/event-dispatcher": "^3.2". My magento composer.lock reference "symfony/event-dispatcher": "~4.1.0"
Per your readme curl-easy is only required with zip file, so I suggest to get rid of if in composer requirement.

**Comment by maciejslawik** [comment]
Not really. Curl-easy is always required, but if you add the module manually you need to manually add the dependency. If you install the module via Composer the dependency is installed automatically. 
The stil/curl-easy requires an old version of Symfony Evend Dispatcher, so for now our is incompatible with Magento 2.3.

**Comment by maciejslawik** [comment]
Related PR:
https://github.com/lizardmedia/varnish-warmer-magento2/pull/8
