### ISSUE TITLE
About Magento 2.3 Support 

### ISSUE THREAD

**Issue by mozgbrasil** [lizardmedia/varnish-warmer-magento2#9]
Hello good afternoon

About Magento 2.3 Support

As images we see that error is displayed when trying to install your module, can you help me

![captura de tela de 2019-02-11 21-03-42](https://user-images.githubusercontent.com/17202780/52599702-85dabb80-2e40-11e9-84f8-aa1c01ff58b7.png)

**Comment by maciejslawik** [comment]
Hello,
I updated the PHP version requirements to fix this problem. Let me know if it helped.

**Comment by mozgbrasil** [comment]
Hello good Morning

The error still persists

According to the images we see that the packagist is not communicating with your repository anymore, so the Composer is downloading lagged version

![captura de tela de 2019-02-12 10-14-59](https://user-images.githubusercontent.com/17202780/52634872-7ba3d600-2eaf-11e9-8739-3058f24309bf.png)
![captura de tela de 2019-02-12 10-15-04](https://user-images.githubusercontent.com/17202780/52634874-7ba3d600-2eaf-11e9-90c8-8dd1af0676d4.png)
![captura de tela de 2019-02-12 10-18-26](https://user-images.githubusercontent.com/17202780/52634896-8e1e0f80-2eaf-11e9-824c-f4c31b703b13.png)

**Comment by maciejslawik** [comment]
The package on packagist should have updated automatically but it didn't. I did it manually.

**Comment by mozgbrasil** [comment]
Thank you my friend, now I was able to install by Composer
